from django.core.exceptions import ValidationError
# from
#
# def refurbishment_validator(refurbishments):
#     for refurbishment in refurbishments:
#         print(refurbishments.name)